import { IShopCard } from '../typing/interfaces.tsx';

const PIZZA_DATA: IShopCard[] = [
  {
    discount: 5,
    popular: true,
    size: 'medium',
    name: 'Magneritana',
    category: 'Spicy pizza',
    price: '8,55 $',
    inCart: false,
    flour: 'thick',
  },
  {
    discount: 10,
    popular: false,
    size: 'small',
    name: 'Pepperoni',
    category: 'Classic pizza',
    price: '7,99 $',
    inCart: true,
    flour: 'thin',
  },
  {
    discount: 5,
    popular: true,
    size: 'big',
    name: 'Quattro Formaggi',
    category: 'Cheese pizza',
    price: '11,50 $',
    inCart: false,
    flour: 'thick',
  },
  {
    discount: 10,
    popular: true,
    size: 'medium',
    name: 'Margherita',
    category: 'Classic pizza',
    price: '9,25 $',
    inCart: false,
    flour: 'thin',
  },
  {
    discount: 15,
    popular: false,
    size: 'small',
    name: 'Vegetariana',
    category: 'Veggie pizza',
    price: '8,75 $',
    inCart: true,
    flour: 'thick',
  },
  {
    discount: 0,
    popular: true,
    size: 'big',
    name: 'Diavola',
    category: 'Spicy pizza',
    price: '12,99 $',
    inCart: false,
    flour: 'thin',
  },
  {
    discount: 0,
    popular: false,
    size: 'medium',
    name: 'Capricciosa',
    category: 'Mixed pizza',
    price: '10,50 $',
    inCart: false,
    flour: 'thick',
  },
  {
    discount: 7,
    popular: true,
    size: 'small',
    name: 'Hawaiian',
    category: 'Fruit pizza',
    price: '8,99 $',
    inCart: true,
    flour: 'thin',
  },
  {
    discount: 12,
    popular: true,
    size: 'big',
    name: 'Calzone',
    category: 'Folded pizza',
    price: '13,25 $',
    inCart: false,
    flour: 'thick',
  },
  {
    discount: 5,
    popular: false,
    size: 'medium',
    name: 'Marinara',
    category: 'Classic pizza',
    price: '9,75 $',
    inCart: false,
    flour: 'thin',
  },
];

export { PIZZA_DATA };
